version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8785:443"
#      - "8786:80"
#      - "8787:81"
      - "8788:82"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
